name: benchmarking_env
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.7.3
  - pandas=1.3.5
  - tensorboard=2.9.1
  - pytorch-lightning=1.6.4
  - torch=1.12.0
  - torchvision=0.13.0
  - scipy=1.6.3
  - numpy=1.21.6
  - scikit-learn=1.0.2
  - cvxpy=1.3.0
  - cvxpylayers=0.1.5
  - networkx=2.6.3
  - ortools=9.3.10459
  - qpth=0.0.15
  - gurobipy=9.5.2
